### ISSUE TITLE
Image Web Worker not working with #hash in URL

### ISSUE THREAD

**Issue by chiefcll** [WebPlatformForEmbedded/Lightning#106]
Using a URL with a hash in it:

http://localhost:8080/#helloWorld

Images loaded via the Image Worker using a relative path fail to load. Image src `./assets/images/img.jpg`

I assume this has something to do with passing in the whole href, which includes the hash
https://github.com/WebPlatformForEmbedded/Lightning/blob/master/src/platforms/browser/ImageWorker.mjs#L24

**Comment by erikhaandrikman** [comment]
see #107

**Comment by g-zachar** [comment]
Hi @chiefcll 

Can you give us more context about your issue? Lightning does not support path format you specified. You can use `./my/path/to_file.jpg` or `my/path/to_file.jpg`, both originate in app's root directory.

Best regards

**Comment by chiefcll** [comment]
Yes - even if using a relative path images fail to load when a hash param is part of the URL

**Comment by g-zachar** [comment]
@chiefcll 

Can you share an example? I've been using Lightning with hashed urls and didn't run into any problems.

Best regards

**Comment by erikhaandrikman** [comment]
@chiefcll any updates? Or can we close this ticket?
