### ISSUE TITLE
Jest Testing Support

### ISSUE THREAD

**Issue by chiefcll** [WebPlatformForEmbedded/Lightning#111]
We're currently using Jest to test our Lightning app and would like to ask for snapshot testing to be officially supported by Lightning: https://jestjs.io/docs/en/snapshot-testing

Ideally, we need some type of Renderer library that we could take an lng.component and pass it to a renderer and not need an lng.application wrapper. Additionally - I should be able to call patch on that component and .toJSON to export some JSON representation of the current component state. 

Just opening this for discussion to make UI testing easier.

**Comment by erikhaandrikman** [comment]
Working on it in: https://github.com/WebPlatformForEmbedded/Lightning/tree/jest-snapshot
Will keep you up to date in this ticket
