### ISSUE TITLE
Underscore in method's signature meaning

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#112]
Hello,

what's the meaning of the underscore in some method signatures?
For example `_template`.
I'm looking for a way to configure [this](https://eslint.org/docs/rules/no-underscore-dangle) rule of ESLint.
Something like:
```
"no-underscore-dangle": ["error", {
        "allow": [
          "_template",
          "_setup",
          "_setState"
        ]
}]
```
There is a list of this methods?
Eventually, this list should be maintained in some way?
Best regards
Mattia

**Comment by g-zachar** [comment]
Hey @MattiaPontonioKineton 

There is no complete list per se. Underscored methods include:
* component hooks like `_template` `_init`, `_setup`, `_setState` ([docs](https://webplatformforembedded.github.io/Lightning/docs/components/overview))
* keys like `_handleRight`, `_handleUp` ([docs](https://webplatformforembedded.github.io/Lightning/docs/focus/keyhandler))
* signals, which can be completely user defined ([docs](https://webplatformforembedded.github.io/Lightning/docs/components/communication/signal))
* focus hooks ([docs](https://webplatformforembedded.github.io/Lightning/docs/focus/focus))
* as well as hooks that that are part of SDK

As you can see, there seem to be no better way forward than disabling the rule you mentioned altogether.

Best regards
