### ISSUE TITLE
Documenting FOCUS | Es: FOCUS :[R]#1:[0]App

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#115]
Can You please document the synopsis FOCUS logs actually present in the console?
Example: 
`FOCUS :[R]#1:[0]App`
Which do the square brackets mean?

**Comment by erikhaandrikman** [comment]
It represent the path to the the component that has focus: https://github.com/WebPlatformForEmbedded/Lightning/blob/a6a83d35ceaa4fe5edaa033130bd9c2d75c7ab58/src/tree/Element.mjs#L1108

[R]=> means root
[0..n] => Means child index

We will add this to the documentation
