### ISSUE TITLE
Pattern to share styles across components

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#116]
Investigating some pattern to create an object of styles properties and share them between components like CSS classes.

**Comment by erikhaandrikman** [comment]
Is this something you are investigating? Or is this is a question?

**Comment by MattiaPontonioKineton** [comment]
Is this something that I'm investigating. 
People that come from CSS probably looking to a way to group styles as same as CSS classes.
I find out two ways:
## Style Component
```
class MenuItem extends Lightning.Component {
// This holds focus, and graphic style
}
export default class MenuItem1 extends MenuItem {
// This holds methods for logic
}
export default class MenuItem2 extends MenuItem {
// This holds methods for logic
}
```
## Style Object
```
const style = {
// This holds graphic style
}
class MenuItem1 extends lng.Application {
    static _template() {
        return {
            ...style
        }
    };
}
class MenuItem2 extends lng.Application {
    static _template() {
        return {
            ...style
        }
    };
}
```
React Native has a built-in class for this purpose: https://reactnative.dev/docs/style
The main goal is to prevent switching logic in ancestors just to force the children to be of the same component for style needs.
Maybe It should be and argoument of the DOC.

**Comment by erikhaandrikman** [comment]
Thanks for thinking along. There are multiple ways of inherting styles and in the future we will add this to our documentation under a tips & tricks or best practices section. We're also thinking about making our documentation open-source so everyone can contribute. Will close this ticket for now.
