### ISSUE TITLE
State Machine from third party

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#118]
Is in discussion the ability or support for external state machines?
Es: https://xstate.js.org/docs/
As I know, React (similar concept) works with Redux using a Third part library:
https://redux.js.org/basics/usage-with-react

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton 

The often problem with third party libraries is they are way too robust in their implementation which negatively affects performance on lower end devices as they were built for desktop in mind, so I don't recommend using solutions that are not lightweight in their nature.

Best regards
