### ISSUE TITLE
Lightning "Getting Started" docs link is broken

### ISSUE THREAD

**Issue by aboyett** [WebPlatformForEmbedded/Lightning#119]
As a user who knows nothing about Lightning I expected the [Getting Started](https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/web) link in the footer of https://webplatformforembedded.github.io/Lightning/ to deliver me to a tutorial on using Lighting. The link is broken (HTTP 404), file appears to now be located at https://webplatformforembedded.github.io/Lightning/docs/gettingStarted-old/web

Digging through the source, it looks like the new [Getting Started SDK or Not](https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/sdkornot) page appears to be the entry point of the new tutorial. I would expect the link on the root Lightning docs page to be updated either to the new location of the old tutorial, or to the entry point of the new tutorial

**Comment by Thomvl** [comment]
Thanks for this report, https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/sdkornot is indeed the new starting point and we will update the link to the new entry point
