### ISSUE TITLE
Specify radius for each corner for a rectangle

### ISSUE THREAD

**Issue by vnarni** [WebPlatformForEmbedded/Lightning#121]
Hi, 
Is there support for drawing rectangle with round corners having different radius on each corner ?
Thanks

**Comment by erikhaandrikman** [comment]
You can specify the radius for each corner: https://github.com/WebPlatformForEmbedded/Lightning/blob/3ff418f0a29f4a521aedbfb2ee754e2bdf967088/src/tools/Tools.mjs#L11

**Comment by vnarni** [comment]
Thanks for the response.

**Comment by erikhaandrikman** [comment]
no problem!
