### ISSUE TITLE
Components set props before children is set

### ISSUE THREAD

**Issue by chiefcll** [WebPlatformForEmbedded/Lightning#122]
Given the following component:
```
SectionsContainer: {
        type: FocusManager,
        direction: 'column',
        selectedIndex: 1,
        signals: {
          selectedChange: '_updateState'
        },
        AmbientRow: {
```
I have a selectedIndex which I'd like to look at the components children in. Unfortunately, the setter for selectedIndex gets called before the children are determined for the component. If I move the selectedIndex prop to the end of the SectionsContainer, it works fine. 

I'd like for the logic to be
Process the component + children - gather any props you don't understand, then apply the props after the components children are determined.

**Comment by g-zachar** [comment]
Hi @chiefcll 

I'm not sure I understand. Can you provide full example of what you're trying to achieve?

Best regards

**Comment by chiefcll** [comment]
I've got a FocusManager class used like such:
```
Component: {
    type: FocusManager,
    direction: 'column',
    signals: {
      selectedChange: 'selectedChangeMock',
    },
    selectedIndex: 1,
    Page1: { type: lng.Component },
    Page2: { type: lng.Component },
    Page3: { type: lng.Component }
  }
```
It sets the _getFocused to point to Page1, 2 or 3 based on the selectedIndex. Now when the component boots up... 

```
set selectedIndex(index) {
    let previousIndex = this.selectedIndex;

    if (index >= 0) {
      if (index < this.children.length) {
        this._selectedIndex = index;
      } else {
        this._selectedIndex = this.children.length - 1;
      }
    } else {
      this._selectedIndex = 0;
    }

    if (previousIndex !== this._selectedIndex) {
      this._previouslySelected = this.children[previousIndex];
    }

    this._refocus();
  }
```
this.children is undefined... However if I do

```
Component: {
    type: FocusManager,
    direction: 'column',
    signals: {
      selectedChange: 'selectedChangeMock',
    },
    Page1: { type: lng.Component },
    Page2: { type: lng.Component },
    Page3: { type: lng.Component },
    selectedIndex: 1,
  }
```
And move selectedIndex at the end, it works fine.

**Comment by g-zachar** [comment]
Hi @chiefcll 

Now I understand, thanks for example. The order of initialisation inside template is not guaranteed, although it makes most sense for it to be sequential. However, the proper way of handling your case would be setting `selectedIndex` inside `_init()` hook which ensures that it's called after template is parsed and components fully constructed.

Best regards

**Comment by chiefcll** [comment]
Understood - I would argue the framework needs to account for this. If I add props to my template that use setters - I shouldn't need to add logic to know if the template has been stamped or not. I want to provide an interface for others to use my component and say `this.tag('FocusManager').selectedIndex = 2` - I'd need to create a work around for setting that on the template and later being able to call it directly after it's attached.

**Comment by g-zachar** [comment]
Hi @chiefcll 

Note that the whole point of having lifecycle hooks in component based frameworks is because vast majority of cases are non-trivial e.g. it's quite common to have child components that are constructed asynchronously as a response to http request. It's very hard to account for all the cases that developer can potentially come up with in the template.

Best regards
