### ISSUE TITLE
Smartphone remote controller

### ISSUE THREAD

**Issue by pabioFavanetto** [WebPlatformForEmbedded/Lightning#125]
Hello,
 it is possible to create a remote tv controller with a smartphone?
if yes, Can you suggest me how to start?

**Comment by erikhaandrikman** [comment]
It is possible. You should take a look at:[websockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API)

When your TV-app and your smartphone join the same websocket server you're able to handle communication between the two users

**Comment by MattiaPontonioKineton** [comment]
I suggest seeing: https://it.wikipedia.org/wiki/Chromecast
I think it uses API exposed in the same subnet (router) via the app Google Home.
But I think that the WebSocket approach is better because You only have to develop the applications server and clients.
