### ISSUE TITLE
Access properties and methods of a Component instance from outside (not from the Framework / App).

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#130]
I have a library that needs to use a [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications) object initialized only in a particular component state (`Multiplayer.Remote`).
Something like:
```
$enter() {
 this.webSocket = new WebSocket("ws://localhost:8080");
}
```
So I need to send messages on the same connection from outside, from callbacks of a state manager.
How Can I access the object?
The instances are somewhere in the global scope?
Keep error handling out of scope for now.
I've also thought about move the instance outside, but I need to start the connection only in this particular state so seem that create the instance of WebSocket is the way to start the connection.
Even my state manager needs to fire a redrawing of the GUI due to particular events (ed: `updateBoardGUI`).

For reference the state manager is: https://xstate.js.org/

**Comment by erikhaandrikman** [comment]
Your WebSocket instance is now a property of your Component instance. If you want to use it from the outside you should make it accessible.

But if you have a reference to the component that created the instance you can access it via: 
```
const c = this.tag("Foo");
c.webSocket.send("Bar");
```

**Comment by MattiaPontonioKineton** [comment]
@erikhaandrikman thanks.
Where are the components references?
Are them in `windows`?

**Comment by erikhaandrikman** [comment]
Well, it all depends on the logic of your App, your app is probably accessible in global scope. But the component that hosts the child that has the `webSocket` property has a reference. I suggest reading: https://webplatformforembedded.github.io/Lightning/docs/renderEngine/elements/children#__docusaurus for more information on accessing children.

**Comment by erikhaandrikman** [comment]
Another suggestion, every `Component` has access to the instance of the application, via:  `this.application` you could also change your logic a bit and add the property to the instance of your application: 

`this.application.webSocket = new WebSocket("ws://localhost:8080");` and if your app is in global scope you can access it via something like: `window.app.webSocket`

**Comment by MattiaPontonioKineton** [comment]
@erikhaandrikman thanks.
`window.app`. is `undefined`.
I need to call `_setState` from an [action](https://xstate.js.org/docs/guides/actions.html#declarative-actions) (a function not-from-Lightning).

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton 

If you look at lightning examples in this repository you'll notice the app instance is created in script tags. That means, for vanilla lightning, it's not a problem to handle reference there. The reason lightning does not expose app instance to global scope is because you could potentially have multiple instances and it's not good architectural pattern in general.

If you're using SDK on the other hand then the problem should be reported there as one of its features is orchestrating lightning apps.

As a workaround, I could suggest to expose your app to global scope yourself e.g. with `window.app = this.application` to have full access but I also strongly advise against such solutions.

Best regards

**Comment by MattiaPontonioKineton** [comment]
@g-zachar thanks for the support. I'm not looking to a way to expose the app from the component.
I'm looking to a way to define my custom components (to make them reusable) and a side feature connects them with other libraries. So I'm looking to the safe path to the instances of the component.
Here's another use case:
```
import { Lightning } from 'wpe-lightning-sdk';
import { interpret } from 'xstate';
import stateNode from './game/machine';
import Utils from './lib/GameUtils';
export default class Game extends Lightning.Component {
constructor(stage) {
		super(stage);
		this.interpreter = interpret(stateNode)
		    .onTransition((state, event) => this._setState(state.value, [
		        event,
		        "other argument"
		    ]));
		this.interpreter.start();
	}
}
```
As see above I have to do the connection with `xstate` in the `costructor` that makes the module **has to be dependent** to XSTATE. 
I want to do this connection **outside** the module, so I need `this` from somewhere.
There is a way to access the `this` from outside the class definition?
