### ISSUE TITLE
Grouping Learning Resources

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#132]
I suggest grouping in a Doc section all the learning resources for new developers thatn want to get started:

- https://github.com/mlapps/lightning-getting-started-docs
- https://github.com/WebPlatformForEmbedded/Lightning-Demo-App
- Other Snippets from issues?

**Comment by erikhaandrikman** [comment]
Thanks for the suggestion! Grouping resources is on our todo list.
