### ISSUE TITLE
Passing a Payload to _setState

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#133]
Is possible to pass a payload of an object to `_setState` function?
## Use case
Passing the `error` to `_setState("Error")`.
Error state patches the colours of the UI and the error message in a box.
Something like: 
`this.webSocket.onerror = error => this._setState('Error', error);`

**Comment by erikhaandrikman** [comment]
Hi, this is currently possible, but i see that it's not been documented properly (we will add it).
Let's follow up on your example. The first parameter in the  `$enter` hook of a state holds an object with [information](https://webplatformforembedded.github.io/Lightning/docs/components/statemachine/events) that identifies the statechange: 

```
class SomeState extends this{
  $enter({ prevState, newState, sharedState}){ ... }
}

```
we're using [Destructing assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

--- 

You can provide a second argument to the `setState` function: https://github.com/WebPlatformForEmbedded/Lightning/blob/d46ae917c68bfd5547787a92c1a6b28d8d56ab34/src/application/StateMachine.mjs#L97 and this needs to be an array (that will be spread as paramaters to the `$enter` hook in your application:

```
this._setState("SomeState", [{a:1, b:2, message:"hi"}, "some string", 12]);
```

and inside your `$enter` hook: 

```
$enter(args, ...payload){
  // payload is an array with the following elements: 
  //  [{a:1, b:2, message:"hi"}, "some string", 12]
}
```
