### ISSUE TITLE
_focus change handler doesnt have full focusPath 

### ISSUE THREAD

**Issue by chiefcll** [WebPlatformForEmbedded/Lightning#134]
As you loop through the focus change handler:
https://github.com/WebPlatformForEmbedded/Lightning/blob/master/src/application/Application.mjs#L107

The focusPath is being created one item at a time. I'd like to know the full focus path in an App level _focus handler.  Setting this._focusPath = newFocusPath two lines above should solve the issue.

**Comment by g-zachar** [comment]
Hi @chiefcll 

This is intended behaviour, whether the design decision was good or bad is up for debate. However, the proposed change is potentially breaking for existing apps, so there must be a very good reason to do it.

Can you share problem you're trying to solve this change would help you with?

Best regards

**Comment by chiefcll** [comment]
At the app level I've created an accessibility screen reader - when Focus changes in the app I want it to get information from the screen on what to read out to a blind user. 

```
 _focus() {
    // Lightning isn't giving us the updated focus path
    let focusPath = this.application.__getFocusPath();
    // let focusPath = this.application.focusPath;
    let lastFocusPath = this._lastFocusPath || [];
    let focusDiff = focusPath.filter(elm => !lastFocusPath.includes(elm));

    let toAnnounce = focusDiff.reduce((acc, elm) => {
      elm.announce && acc.push(elm.announce());
      return acc;
    }, []);

    focusDiff.reverse().reduce((acc, elm) => {
      elm.announceContext && acc.push(elm.announceContext());
      return acc;
    }, toAnnounce);

    this._lastFocusPath = focusPath.slice(0);
    toAnnounce = toAnnounce.filter(a => a);
    if (toAnnounce.length) {
      speak(toAnnounce);
    } else {
      speak('Nothing');
    }
  }
```

Doing this at the app level I don't have the full focus path yet to go through the elements.

**Comment by g-zachar** [comment]
@chiefcll 

I see, this is very unusual use case. Nevertheless, your approach is correct, even though `__getFocusPath` method is private, it's safe to use.

Best regards
