### ISSUE TITLE
TypeError: Cannot read property 'ctx' of undefined

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#135]
Using this component throws an error.
```
export default class Game extends Lightning.Component {
	constructor() {
		super();
	}
}
```
I think is need to be fixed even if `_construct` exists.

**Comment by erikhaandrikman** [comment]
This is already possible, but you're missing the `stage` argument that you need to provide as parameter to the `super()` call: 

```
constructor(stage){
    super(stage);
}
```
