### ISSUE TITLE
State Machine [Features]

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#138]
Hello,
I'm looking to these concepts into the build-in state machine:

- Events: switch state or call functions due to [events](https://developer.mozilla.org/en-US/docs/Web/API/Event). [Dispatching](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) events.
- Actions: fire side-effect functions due to events, with event available in the scope of these functions
- Transition: listen to state changes
- Guards: functions that do or do not block a transition

There are some functions available but not yet documented in this field?
## Goal
Implementing [this](https://xstate.js.org/viz/?gist=0d00a87109d77718045fd39ce75cc0ed) all using Lightning.

Best regards
Mattia

**Comment by erikhaandrikman** [comment]
A richer statemachine is on our todo list, will keep you up to date
