### ISSUE TITLE
Passing State Methods as Callbacks not working

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#141]
![image](https://user-images.githubusercontent.com/44380480/77656937-de054c00-6f74-11ea-9ee5-0690861e78fb.png)
Seems that if I define a method in a State Class 
```
static _states() {
  return [
   class State extends ParentState {
    $enter() {
    this.eventTarget.addEventListener('EVENT', this.method); // NOT WORKS
    this.method(); // WORKS
   }
   method(){}
  }
 ]
}
```
and I call it in `$enter` with `this.mehod()` it works. 
If I pass I as callback in another function It will be not called.
- Are this related to `StateMachineRouter`?
- Maybe the function is not ever defined?
- Is possible to define methods in State classes?

**Comment by g-zachar** [comment]
Hi @mattiapontonio,

you can ensure proper context binding e.g. by passing `() => this.method()` to event listener. The context within state machine is a complex matter, but we hope to put proper documentation for lightning's state machine in place soon enough.

Best regards
