### ISSUE TITLE
Documenting context within state machine

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#144]
Hi @mattiapontonio,

you can ensure proper context binding e.g. by passing `() => this.method()` to event listener. The context within state machine is a complex matter, but we hope to put proper documentation for lightning's state machine in place soon enough.

Best regards

_Originally posted by @g-zachar in https://github.com/WebPlatformForEmbedded/Lightning/issues/141#issuecomment-604499527_

I suggest:
- the use of [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this), when and how even in nested states
- the use of [super](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super), when and how even in nested states
- state-specific method signatures

**Comment by erikhaandrikman** [comment]
I will close this ticket for now
