### ISSUE TITLE
Text rendering issue, getting black screen

### ISSUE THREAD

**Issue by lk-mlogical** [WebPlatformForEmbedded/Lightning#148]
Hi Team,

I am trying to render the simple text content (END USER LICENSE AGREEMENT) using the following code. 

`static _template() {
        return {
            ContentWrapper: {
                w: 540, h: 890, x: 30, y: 89, clipping: true,
                Content: {
                    w: 540, 
                    text: { 
                       text: 'READ CAREFULLY THIS END USER LICENSE AGREEMENT BEFORE accessing, ..............', // Note: the content continues with a huge paragraphs 
                       textColor: 0xffACACAC, 
                       fontFace: 'Roboto', fontSize: 24, lineHeight: 34, wordWrapWidth: 540 }
                }
            }
        }
    }
    
    _init() {
        this.tag('Content').on('txLoaded', () => {
            console.log('renderText: ', this.tag('Content').renderHeight);
        });
    }`

If the renderHeight of the Content tag exceeds 4000, then the screen gets black, the application doesn't render the text. 

Is there any other approach to render multiple paragraphs?

**Comment by Thomvl** [comment]
Hi @lk-mlogical ,

Unfotunatly this is not a Lightning bug, but rather a WebGL limitation.

As of today you will need to cut the text in parts, perhaps in paragraphs and render them seperately. Perhaps the Flexbox layouting as a column will solve this..
