### ISSUE TITLE
Handle fire anchestor depending on state

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#149]
Is possible to fire anchestors and handle that differently depending on state?
In my case I'm using the same component to handle enter but in one state of the parent I need to make some API calls otherwise in another state I do not need that.

**Comment by erikhaandrikman** [comment]
Yeah,

```
static _states(){
 return [
 class Foo extends this{
    // will call this in state: Foo on fireAncestors("$bar")
    $bar(){ }
  },
  class Foo1 extends this{
    // will call this in state: Foo1 on fireAncestors("$bar")
    $bar(){ }
  }
] 
}
```

**Comment by mattiapontonio** [comment]
Thanks!

I want to split hairs saying that in this case states are siblings and not anchestors by each other but of course the feature of communication is usefull! I'll implements It ASAP.

Best regards
