### ISSUE TITLE
get text() on the View returns a texture, while it should return the text (string)

### ISSUE THREAD

**Issue by salmon-charles** [WebPlatformForEmbedded/Lightning#15]
```javascript
 get text() {
        if (this.texture && (this.texture instanceof TextTexture)) {
            return this.texture.text; // proposed fixed
            // return this.texture; 
        } else {
            return undefined;
        }
    }
```

**Comment by basvanmeurs** [comment]
The text property refers to an object. Just like when setting it (item.text = {fontSize:24,text:"hello"}) it is logical that item.text returns that same settings object (which is the TextTexture object), or statements like item.text.fontSize=24 would no longer work.

item.text = "hello" is a shorthand purely for backwards compatibility
