### ISSUE TITLE
Log the name of the state

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#150]
Is possible to log the name of the state for debugging pourpose?
Something like:
```
import { Log } from 'wpe-lightning-sdk';
....
$enter() {
  Log(this.theNameOfThisState);
}
```

**Comment by erikhaandrikman** [comment]
There is an accessor available on the component instance that will return the current state: `this.state`

**Comment by mattiapontonio** [comment]
@erikhaandrikman thanks.
I suggest mentioning here:
https://webplatformforembedded.github.io/Lightning/docs/components/statemachine/statemachine

**Comment by erikhaandrikman** [comment]
Thanks for the tip
