### ISSUE TITLE
Use cases for Component events

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#152]
Can You please provide a use case for each of the Component events?
https://webplatformforembedded.github.io/Lightning/docs/components/overview

Es:
- When used to set properties to children
- When can I use `this`
- ...

**Comment by erikhaandrikman** [comment]
All events are hooks that you can use to your benefit, you want to do some clean up logic when your component gets deleted? Use `_detach`. You want to invoke some logic when your component comes with in viewport for the first time? Use `_firstActive` etc.

You will find a description of when each event will be called

**Comment by mattiapontonio** [comment]
@erikhaandrikman thanks for the support.
I want to take this issue open in order to propose to improve documentation in this topic.
My proposal is a dedicated page:
https://webplatformforembedded.github.io/Lightning/docs/components/events

## Other questions

- I've implemented a `Component` (`Cursor`) that when is deactivated became red and the common handlers have no effects. Can I use `_enable()` and `_disable()` hooks?
- How can I fire these hooks programmatically? For example, `patching` some template `keys` to `null`? There is another way?
- More in general, what kind of graphic effects each event implies?

I'm looking to understand in order to not-reimplement what is just ready to use.

Best regards
Mattia
