### ISSUE TITLE
Documenting Element class

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#155]
Should be good to have a page for `Element` class in order to learn how to construct them and use it for example in `childList` methods.
Rif https://webplatformforembedded.github.io/Lightning/docs/renderEngine/elements/children
As same as [Component](https://webplatformforembedded.github.io/Lightning/docs/components/overview) class.

**Comment by mattiapontonio** [comment]
For example I'm trying something like this but not working...
```
	set players(players = new Players()) {
		// TODO forzare con setAt(item : Element, index : number) alla posizione playerId
		Array.from(players).forEach(player => {
			const item = (new Lightning.Element)(this.stage);
			Object.assign(item, {
				type: Position,
				color: player.color,
				playerId: player.id,
				marker: player.marker,
				playerName: player.name,
				w: (900 / 3), // TODO computare
				h: (900 / 3) // TODO computare
			});
			const index = player.id;
			this.tag('Positions').childList.setAt(item, index);
		});
	}
```
## Error
```
TypeError: Cannot read property 'ctx' of undefined
    at new ElementCore (lightning.es5.js:4131)
    at new Element (lightning.es5.js:9408)
    at StateMachineRouter.<anonymous> (Game.js:251)
    at Array.forEach (<anonymous>)
    at StateMachineRouter.set (Game.js:250)
    at StateMachineRouter._build (App.js:78)
    at new Component (lightning.es5.js:12641)
    at _default$1.<anonymous> (appBundle.es5.js:240)
    at new _default$1 (Splash.js:3)
    at ElementChildList.createItem (lightning.es5.js:9380)
```

**Comment by erikhaandrikman** [comment]
Hey, will put this on the backlog, but for now i suggest taking a look at this basic renderer example: 
https://github.com/mlapps/basic-renderer/blob/master/render.html

**Comment by mattiapontonio** [comment]
@erikhaandrikman thanks.
This fixes my issue:
```
add(move = new Move()) {
    const m = this.application.stage.c({
        type: Marker,
        Label: {
            text: {
                text: move.marker
            }
        },
        ref: move.ref,
        ...move
    });
    this.childList.add(m);
}
```
I want to suggest to made `Element` class kind of pure because I cannot do something like:
```
const move = new Move();
const move = new Move();
```
if I have not a reference to the stage.
It should be good even for testing purposes.

## Out of scope
What is the difference between `Element` and `Component`?

Closable for me.
Best regards
Mattia
