### ISSUE TITLE
Go back to initial properties

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#157]
In my Component I've setupped a Disabled state:
```
class Disabled extends this {
    $enter() {
        const config = {
            color: 0xFFFF0000
        };
        this.patch(config);
    }
    $exit() {
        const config = {
            color: this.color
        };
        this.patch(config);
    }
    _handleEnter() {
        this.animations['enter'].start();
    };
}
```
With this code, exiting the state do not reset the color to the initial value, that is passed from outside (from parent in a children mapping).
- How I can achieve this?
- I've to save the value in another property?

**Comment by erikhaandrikman** [comment]
It will indeed not reset the color because in the `$exit` hook you're patching the color to what it currently is, you could change it around to something like this: 

```
$enter() {
    this._storeColor = this.color;
    const config = {
        color: 0xFFFF0000
    };
    this.patch(config);
}
$exit() {
    const config = {
        color: this._storeColor
    };
    this.patch(config);
}
```

**Comment by mattiapontonio** [comment]
Thanks for the support.
I understand that the properties Is overidden by state.
Which method should be responsable to set `_storeColor`?
I'm my case this data comes from outside. 
Maybe a public property with a setter is a good thing.
With the underscore You meant kind of "private"?

**Comment by mattiapontonio** [comment]
I understanded the logic. Think is better to manage color from outside as a property or use setters.
