### ISSUE TITLE
this is window instead of Lightning.Component

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#162]
I've implemented a kind of logic of _repetitive update_ in a particular state of a component:
```
$enter() {
	this.interval = setInterval(this.sync, 1000);
}
```
This is the handler:
```
async sync() {
    const players = new Players(); // TODO ragionare
    await players.get(); // this update players from REST API
    // here (this == window) somethimes.
    this.players = players;
}
```
The problem is that this setter now not working. It works if I call from for example `_init` but not from the callback of `setInterval` because this in this case is window instead of the component itself.
```
set players(players = new Array()) {
    this.tag('Game').players = players;
    this.tag('ScoreBoard').players = players;
}
```
I've to bind the callback?
There are other patterns?
Best regards
Mattia

**Comment by erikhaandrikman** [comment]
This is not really a Lightning related question or issue, but you forgot to [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) the scope, so `this` in your sync method wil point to `window`

```this.interval = setInterval(this.sync.bind(this), 1000);```

Will fix your issue

**Comment by mattiapontonio** [comment]
@erikhaandrikman this indeed fixes my issue.
Anyway, after some work, I'm focused on prevent to define methods that are not to be exposed to parent so the scopes in the official methods are working good.
Thanks for the support.
Mattia
