### ISSUE TITLE
Setting w and h from parent

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#165]
Hello,
developing Tic Tac Toe I want that the `Field` and the lines that are `children` of the `Field` can fe configured in terms of `w` and `h` from parent.
I want to preserve the `smoothing` of the lines in the `active` event.
But, `this.w `and `this.h` are undefined in the event, why? How I can achieve that?
REF: https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/development-tictactoe
REF: https://webplatformforembedded.github.io/Lightning/docs/renderEngine/elements/children
This is the `Field` Component, the `w` and `h` are forwarded via setters by the Game parent.
```
import { Lightning } from 'wpe-lightning-sdk';

// Questa classe definisce le linee del campo con animazione, etc..
export default class extends Lightning.Component {
	static _template() {
		return {
			children: [
				{
					// 1 ORRIZONTALE
					rect: true,
					h: 8
				},
				{
					// 2 ORRIZONTALE
					rect: true,
					h: 8
				},
				{
					// 1 VERTICALE
					rect: true,
					w: 8
				},
				{
					// 2 VERTICALE
					rect: true,
					w: 8
				}
			]
		};
	}
	_active() {
// this is the only way that I've found to provide defaults
		const w = this.w || 100;
		const h = this.h || 100;
		this.children.forEach((line, index) => {
			const a = index < 2 ? 'w' : 'h';
			const b = index < 2 ? w : h || 100;
			line.setSmooth(a, b, {
				duration: 0.7,
				delay: index * 0.15
			});
		});
	}
	set h(h = new Number()){
// if I use h from template here there is an error because the template is not ready
		this.children[0].patch({y: (h / 3 * 1) - (8 / 2)});
		this.children[1].patch({y: (h / 3 * 2) - (8 / 2)});
	}
	set w(w = new Number()){
// if I use w from template here there is an error because the template is not ready
		this.children[2].patch({x: (w / 3 * 1) - (8 / 2)});
		this.children[3].patch({x: (w / 3 * 2) - (8 / 2)});
	}
}
```
The error if I provide defaults from `template` object literal or `construct `event:
```
TypeError: Cannot read property 'patch' of undefined
    at StateMachineRouter.set (Field.js:52)
    at StateMachineRouter._construct (Field.js:32)
    at StateMachineRouter.__construct (lightning.es5.js:12757)
    at new Component (lightning.es5.js:12634)
    at _default.<anonymous> (appBundle.es5.js:240)
    at new _default (Cursors.js:5)
    at Object.eval [as f] (eval at parseTemplate (lightning.es5.js:13037), <anonymous>:31:17)
    at new Component (lightning.es5.js:12639)
    at _default.<anonymous> (appBundle.es5.js:240)
    at new _default (Markers.js:4)
```

**Comment by g-zachar** [comment]
@mattiapontonio 

I'm not sure I understand what you mean by preserving the smoothing.

However, dimensions relative to parent are straightforward using [dynamic functions](https://webplatformforembedded.github.io/Lightning/docs/renderEngine/elements/positioning).

Also, you shouldn't try to override any of lightning's elements properties unless they are hooks specifically designed for it (`w` and `h` properties are not).

Example: https://jsfiddle.net/w14xot6g/1/

**Comment by mattiapontonio** [comment]
@g-zachar thanks You, this is the solution that I was looking for!
I didn't read about it. 
:)
Thanks again. :)
![image](https://user-images.githubusercontent.com/44380480/80612589-72fbd900-8a3c-11ea-9e2a-655cc423e190.png)
