### ISSUE TITLE
inherit function

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#166]
Referring to this: https://github.com/WebPlatformForEmbedded/Lightning/issues/165
Proposal:
```
export const inherit = f => f;
```
from `wpe-lightning-sdk`
To be used as a kind of keyword in `_template`.
## Example
```
import { inherit } from 'wpe-lightning-sdk';
export default class extends Lightning.Component {
	static _template() {
		return {
			w: inherit,
			h: inherit,
		};
	}
}
```

**Comment by michielvandergeest** [comment]
Feel free to use this approach in your own app code, but I don't think this is something we should add to Lightning Core or the Lightning SDK.
