### ISSUE TITLE
Dynamic properties are functions instead of values

### ISSUE THREAD

**Issue by mattiapontonio** [WebPlatformForEmbedded/Lightning#168]
When I use 
https://webplatformforembedded.github.io/Lightning/docs/renderEngine/elements/positioning#dynamic-calculations
Ex:
```
	static _template() {
		return {
			players: players => players, // expected [] from parent
		};
	}
```
sometimes the value that I'm expecting is not the value (for example an array of players inherited form parent) but a "bound function".
Ex:
```
bound players
ƒ bound players()
```
I can't figure out how to fix that.
This causes an error for example in the mapping of the children.
## Scenario
Imagine that we have multiple descendants, and in one point of the chain the players are updated, expecting that the data be forwarded to all children that have the dynamic calculation settled, without provide a setter for this opeartion.

**Comment by g-zachar** [comment]
@mattiapontonio 

Dynamic functions apply only for certain properties: `w`, `h`, `x` and `y`

Best regards
