### ISSUE TITLE
issue with npm i https://github.com/WebPlatformForEmbedded/Lightning-node.git --save

### ISSUE THREAD

**Issue by wilberhdez** [WebPlatformForEmbedded/Lightning#17]
I'm getting the following error.  I tried installing the missing packages  and still same issue.

/Lightning$ npm i https://github.com/WebPlatformForEmbedded/Lightning-node.git --save

> canvas@2.3.1 install /repos/Lightning/node_modules/canvas
> node-gyp rebuild

Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.15.0-48-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /repos/Lightning/node_modules/canvas
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN wpe-lightning@1.0.4 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lab/.npm/_logs/2019-05-06T22_01_18_937Z-debug.log

**Comment by dimaj** [comment]
just solved it by doing this:
1. Followed pre-req installation of canvas: https://github.com/Automattic/node-canvas#Installation
2. ran `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig` (on OSX, I had to augment that by including: `/usr/local/opt/libffi/lib/pkgconfig` at the end
3. Had to downgrade my installation of node from 12 to 10

After these steps, got it installed

**Comment by wilberhdez** [comment]
Somehow I think is easier following the "Lightning-SDK-blueprint" approach. It worked for me -
https://github.com/WebPlatformForEmbedded/Lightning-SDK-blueprint

Anyone know the difference between -
Lightning-SDK-blueprint
Lightning-SDK

**Comment by erikhaandrikman** [comment]
Hi,

The main difference is that Lightning-SDK-blueprint has a dependency on Lightning-SDK, so you need to install the module for your app to work. This provides a better way to update the SDK version in the future. So this repo acts as a "blueprint" for developers to start working with Lightning.

Lightning-SDK uses a concatenate version of Lightning and the actual Lightning source can be found in: https://github.com/WebPlatformForEmbedded/Lightning

**Comment by g-zachar** [comment]
I'm closing this issue for now, please reopen if still relevant.
