### ISSUE TITLE
CORS Issue in loading image from s3 bucket

### ISSUE THREAD

**Issue by stenalpjolly** [WebPlatformForEmbedded/Lightning#22]
@basvanmeurs @thiblahute @Ms2ger @clopez @kuscsik 

CORS error while loading images from S3 bucket.

<img width="1432" alt="Screen Shot 2019-07-05 at 10 19 35 AM" src="https://user-images.githubusercontent.com/8219855/60698733-7141b180-9f0e-11e9-9340-401ef8333b40.png">

`Access to XMLHttpRequest at 'https://s3-eu-west-1.amazonaws.com/xxxxxx.jpg' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`texture load error Image load error https://s3-eu-west-1.amazonaws.com/xxxxxx.jpg
onError @ lightning-web.js:3077
(anonymous) @ lightning-web.js:2957
image.onError @ lightning-web.js:13425
error @ lightning-web.js:13153
error @ lightning-web.js:13104
_worker.onmessage @ lightning-web.js:13083
`

**Comment by woutermeek** [comment]
@stenalpjolly this is related to the backend. The backend should serve the correct CORS headers, this is not something which can be solved within Lightning.

Please find more info [here](https://developer.mozilla.org/nl/docs/Web/HTTP/CORS)
