### ISSUE TITLE
DRM support

### ISSUE THREAD

**Issue by MykhailoDz** [WebPlatformForEmbedded/Lightning#23]
Hello Team, could you tell me, does your internal Player component supports Secure Smooth/Dash Streaming using PlayReady/Widevine DRM?

@thiblahute @Ms2ger @basvanmeurs @clopez 

thanks

**Comment by woutermeek** [comment]
Hi @MykhailoDz,

In combination with Lightning you can use HTML5 videotag and the EME spec to handle DRM protected content. There is no specific functionality in Lightning to handle video and/or DRM content.
