### ISSUE TITLE
How can have letter wrapping for text

### ISSUE THREAD

**Issue by stenalpjolly** [WebPlatformForEmbedded/Lightning#26]
For the text component, 

we have the option of wrapping it by providing wordWrapWidth. But if a single long word is given then, it becomes empty

Eg:
> **Bigsampleword**

Expected
>**Bigsam...**

Actual
> **Empty**

**It would much help if we have an option to wrap with letters rather than omitting the complete word**

**Comment by erikhaandrikman** [comment]
Hi, can you provide some example code to reproduce? If i try i just get an output of the complete word (which is also not what you want) but is doesn't output nothing. Lightning's wrapText method tries to split on full words. We will add this functionality to our backlog and inform you in this thread when it's available

**Comment by stenalpjolly** [comment]
@erikhaandrikman, Please check below code

```js
    static _template() {
        return {
            y: 10,
            ExamplanationText:{
                text:{
                    text: "SAMPLETEXT",
                    maxLines: 1,
                    wordWrapWidth: 150
                }
            },
            Reference:{
                w: 150,
                h: 4,
                rect: true,
            }
        }
    }
```

Expected: 
> SAMPLE..

ACTUAL:
> SAMPLETEXT
