### ISSUE TITLE
image on load callback

### ISSUE THREAD

**Issue by AndriyShpyra** [WebPlatformForEmbedded/Lightning#27]
Hello Team!
Is there a way to know when the  image texture has been loaded and pass a callback function ?

**Comment by erikhaandrikman** [comment]
hey! Yeah you can use the on txLoaded event: 

`this.tag("MyComponent").on("txLoaded",()=>{
 // loaded
});

this.tag("MyComponent").on("txError",()=>{
 // error
}):
`

**Comment by AndriyShpyra** [comment]
Thanks!
