### ISSUE TITLE
3D support in lighnting 

### ISSUE THREAD

**Issue by TheCodeBeginner** [WebPlatformForEmbedded/Lightning#34]
Hi Team,

I would like to know if z-axis property can be brought in to a lightning component, without using any external library such as three.js .

**Comment by g-zachar** [comment]
Hi @TheCodeBeginner, what is exactly you want to achieve?

**Comment by erikhaandrikman** [comment]
Can we close this ticket?

**Comment by g-zachar** [comment]
Yeah, I guess we're not getting an answer. @TheCodeBeginner, please reopen if it's still relevant.
