### ISSUE TITLE
Get text width

### ISSUE THREAD

**Issue by yuraantonov11** [WebPlatformForEmbedded/Lightning#38]
Hello, how can I get the width of the text element? I can get the correct value only after the text is rendered on the page.

**Comment by g-zachar** [comment]
Hi @yuraantonov11 , I don't think there's straightforward answer to that. What do you need such information for?

**Comment by yuraantonov11** [comment]
@g-zachar, I want to get the text width because I need to set the width of the next element after the text.
In this picture, I have a dynamic label length and width.
![image](https://user-images.githubusercontent.com/9784945/64245859-6b6b4b00-cf14-11e9-9460-85aefc4dfe53.png)

**Comment by erikhaandrikman** [comment]
Well since everything is a texture you can do the following: 

`// force a texture load
this.tag("MyTextLabel").loadTexture();
// get width of the texture
const width = this.tag("MyTextLabel").renderWidth;`

**Comment by g-zachar** [comment]
@yuraantonov11 You should be able to build it using flex layout and not bother manually calculating width.
