### ISSUE TITLE
Long text render issues

### ISSUE THREAD

**Issue by AndriyShpyra** [WebPlatformForEmbedded/Lightning#42]
Hello
I have faced render issues when the long text should be displayed 
Instead of showing actual text, the black screen is being rendered (wordWrapWidth was predifined).
Is there a way to fix it ?
![Знімок екрана 2019-09-12 о 6 38 13 пп](https://user-images.githubusercontent.com/49644516/64799109-cf34ea00-d58c-11e9-8d22-3151fa6f91a6.png)
![Знімок екрана 2019-09-12 о 6 41 16 пп (2)](https://user-images.githubusercontent.com/49644516/64799213-060b0000-d58d-11e9-846c-5cd3b7662456.png)

**Comment by g-zachar** [comment]
@AndriyShpyra What's the size of text block you're mentioning? Can you provide code snippet? Also, what platform are you running Lightning on?

**Comment by AndriyShpyra** [comment]
Size of text block   depends on the response from an api, it can be around 600 000 symbols.

`class TextDemo extends lng.Application {
    _init() {
        this.patch({
            x: 50,
            y: 50,
            Text: {
                text: {
                    wordWrapWidth: 600,
                    textColor: 0xffff00ff,
                    fontSize: 36,
                    text: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Augue ut lectus arcu bibendum at varius vel pharetra vel. Amet mattis vulputate enim nulla aliquet. Ac turpis egestas integer eget aliquet. Potenti nullam ac tortor vitae purus faucibus. Duis ut diam quam nulla. Posuere lorem ipsum dolor sit. Faucibus ornare suspendisse sed nisi. Scelerisque felis imperdiet proin fermentum leo vel orci. Faucibus in ornare quam viverra orci .....and a lot more tex}
            }
        })
    }
}

const options = {stage: {w: window.innerWidth, h: window.innerHeight, useImageWorker: false}};
const app = new TextDemo(options);
document.body.appendChild(app.stage.getCanvas());`

**Comment by erikhaandrikman** [comment]
Probably you hit the max texture size and the texture will not be rendered, a valid solution would to split the text up in chunks and use some form of pagination

**Comment by erikhaandrikman** [comment]
@AndriyShpyra  Can we close the ticket?

**Comment by g-zachar** [comment]
We actually could try solving it on Lightning's end, for example by doing text chunking text into smaller pieces and composing several textures. This could be increasingly a problem, because different platforms have different GL capabilities and code that works on desktop browser or even existing low end platforms would break when hitting target platform.

**Comment by erikhaandrikman** [comment]
Good suggestion, but what are we going to do after all the textures are created? We would end up with a batch of textures and only one them would be visible. We then need to offer additional functionality to display one after the other, and the question is if it will match the expectation.

**Comment by AndriyShpyra** [comment]
Thanks for help!
It would be cool if such functionality was added to Lightning

**Comment by g-zachar** [comment]
I analysed the possibilities and unfortunately creating complex text component would not be a good idea.

For one, many developers are used to current way of representing text via texture and introducing different way (e.g. text element) would introduce unnecessary confusion.

Additionally, it would probably take some time before such element would become stable and bug free and at this point and is good candidate for next major release but not as a feature for current one.

And to answer your initial question, to avoid such bugs from occuring it is recommended to create textures that do not exceed viewport dimensions.
