### ISSUE TITLE
Are State Classes Required To Extend 'this' and to be declared inside of the static _states() method?

### ISSUE THREAD

**Issue by im-bob-loucans** [WebPlatformForEmbedded/Lightning#43]
I would like to extract state classes into their own file,  but the examples all show the state class being declared on the fly and extending `this`.   Is this a required pattern?

**Comment by im-bob-loucans** [comment]
If its required request that the documentation be updated to reflect this constraint,  Thanks.

**Comment by g-zachar** [comment]
Hi @im-bob-loucans,

while Lightning does enforce some of its patterns, as long as you follow JS semantics you should be fine.

So for example:
```js
{color: 0xff000000}
```
would be semantically equivalent to:
```js
const COLOR_BLACK = 0xff000000;
...
{color: COLOR_BLACK}
```

Coming back to states, they mainly depend on class expressions and context resolution of static methods:
```js
static _states() {
    return [
        class MyFirstState extends this {
            _handleEnter() {
                // overwrites root function when we are on this state
            }
        }
    ]
}
```
which could also be represented like that:
```js
const stateFactory = function(cls) {
    return class MyFirstState extends cls {
        _handleEnter() {
            // overwrites root function when we are on this state
        }
    }
}

static _states() {
  return [stateFactory(this)]
}
```

So, while following examples is probably safest way to avoid potential issues e.g. with context resolution, it is by no means enforced.

(More extensive example: https://gist.github.com/g-zachar/580094a60c0e27a0396e0745fae6cd2c)

Let me know if this answers your question.

**Comment by im-bob-loucans** [comment]
Thanks for the info.   I followed the factory pattern you provided.
