### ISSUE TITLE
Remove Post-Install Rollup Task, Provide Pre Built `lightning-web.js`

### ISSUE THREAD

**Issue by im-bob-loucans** [WebPlatformForEmbedded/Lightning#45]
Is it possible to provide a pre-built and tested version of the `lightning-web.js` rather requiring it be built as part of the npm ci on the consumer side?

Some benefits would include:
1.  faster build times for consumers
2. assurance that the library consumed is the same regardless of environment
3. assurance that the library, code and test all align and are the result of a build process.
...

possibly publishing to npm as part of a build would resolve.

**Comment by g-zachar** [comment]
Yes, this is something we'd like to do at some point.

**Comment by im-bob-loucans** [comment]
thanks for the update

**Comment by g-zachar** [comment]
Lightning is now published on npm with both standard and minified UMD versions and es6 module.

For now, the builds target ES6 compliant environments, but if there is demand for ES5 builds we will move towards supporting that as well.

**Comment by imrobertloucans** [comment]
@g-zachar  - can you point me to the npm page for the component?

**Comment by imrobertloucans** [comment]
found it.  wpe-lightning 👍
