### ISSUE TITLE
Instead of moving the focus to the items, items are scrolling to the focus

### ISSUE THREAD

**Issue by gotti330** [WebPlatformForEmbedded/Lightning#47]
we are using flex layout in our project and the requirement is to focus each item if I click on down arrow.
To focus we are using setIndex() 
For list we are using flex :{ direction: 'column }
Expected Behaviour: focus should move to the end of the list
Current Behaviour: list is moving to the focus
Due to this some space is creating at the end of the scroll

Please let me know if there is any solution to fix this issue.

Thanks in advance 👍

**Comment by erikhaandrikman** [comment]
Can you provide a little more context about the implementation? Maybe share a working example?

**Comment by gotti330** [comment]
Sure.After adding the list component in our project we are facing this issue.
**we used Flex for the items.**
 static _template() {
        return {
            Items: {
                flex: {direction: 'column'},
            },
        };
    }
 get active() {
        return this.tag('Items').childList._items[this._childIndex];
    }
**And also used setIndex() for the list of items:**
 _setIndex(newIndex) {
        this._itemsIndex = newIndex;
       const childList = this.tag('Items').childList;
        const currentId =
            this._items[this._itemsIndex].id();
        for (let i = 0; i < childList._items.length; i++) {
            const id = childList._items[i].item.id();
            if (id === currentId) {
                this._childIndex = i;
                break;
            }
        }
  const newY =
            this._childIndex < 1 ? 0 : -(this._childIndex * (this.active.renderHeight) - 135);
        this.tag('Items').patch({y: newY});
    }
  _newItem(item) {
        return {
            w: 669, h: 135,
            clipping: true,
            flexItem: {marginTop: 0},
            item: item,
            type: item.type,
        };
    }
  _focus() {
        this._setIndex(this._itemsIndex);
    }
  _getFocused() {
        return this.active;
    }
}
This is the screen shot for the app before adding the list component

[screenshots.zip](https://github.com/WebPlatformForEmbedded/Lightning/files/3621482/screenshots.zip)

After adding the list component we are getting the focus issue as you can see in the screen shot the list is moving upwards and there is a gap in the screen.
But before adding the list component we did not faced this issue.

please let me know.

Thanks.

**Comment by erikhaandrikman** [comment]
There is indeed a solution to prevent this, the problem can be found in this specific part of code: 

```
this._childIndex < 1 ? 0 : -(this._childIndex * (this.active.renderHeight) - 135);
this.tag('Items').patch({y: newY});
```

You are always calculate and set the new y position of the items list, despite the fact if we reach some of the last items. You can fix this in a couple of ways: 

```
// we do always store the new index because this is used
// the move the focus path to the correct item
this._itemsIndex = newIndex;
// grab the height of the list
const listMaxHeight = this.tag("Items").finalH;
// define the height of the renderable viewport
const viewportHeight = 1080;
// calculate the max y position we want to scroll
const maxYPosition = listMaxHeight - viewportHeight;
// calculate the new position items position
const newY = newIndex< 1 ? 0 : -(newIndex * (this.active.renderHeight) - 135);

// we only set the new y position of the list
// if it's lower then max position we want to scroll
if(Math.abs(newY) < maxYPosition){
    this.tag('Items').patch({y: newY});
}
```
Let me know if this works out for you

**Comment by gotti330** [comment]
Thanks for the reply.

It worked to adjust the list items.But I'm still have the issue with the focus.When I'm changing from first channel to second channel the focus is shifting when I go to the third channel the focus is not moving just list element is moving likewise after 10 channels again the focus is moving.  I added a video clip for better understanding.


[File from iOS.zip](https://github.com/WebPlatformForEmbedded/Lightning/files/3627748/File.from.iOS.zip)

Thanks

**Comment by erikhaandrikman** [comment]
I think i kind get the idea where you want to work to, you only want to list to move when it reached the bottom of the screen? Also the focus is shifting from one element to the next there are just 2 seperate things happening: 

1: the new focuspath is being calculated / and changed
2: the list is moving.

The moving of the list has no relation to the focus change (keep in mind, the focus delegation is only used for letting Lightning know which component is active and so should handle the key events).

In your example you decreasing / increasing an index respectively via _handleUp and _handleDown.
So the focus is changing from one element to the other but i think the list is just not scrolling as you want i to be. You can tweak the behaviour of the list so it maybe only moves when you try to focus an offscreen element.

Hope this clear things up a bit.

**Comment by erikhaandrikman** [comment]
You could change the code a bit to this: 

```
// we do always store the new index because this is used
this._itemsIndex = newIndex;
// grab the height of the list
const listMaxHeight = this.tag("Items").finalH;
// define the height of the renderable viewport
const viewportHeight = 1080;
// defines the items we can show per page
const itemsPerPage = Math.floor(viewportHeight / 135);
// defines page height
const pageHeight = itemsPerPage * 135;
// calculate current "page" in which the current focused is
const currentPage = Math.floor(newIndex / itemsPerPage);

// check if the new calculated pageindex if different
// from the stored page index
if (currentPage !== this._storedPage) {

    // calculate the new position for the items list
    let newYPosition = pageHeight * -currentPage;

    // calculate the difference between total items height
    // and the amount of pixels that we've moved the list
    // we're going to use it for aligning list to the bottom
    const diff = listMaxHeight - (Math.abs(newYPosition));

    // if the difference is lower then the viewportHeight
    // we add the remainder to the new position, resulting
    // a position that aligns the list to the bottoms
    if (diff < viewportHeight) {
        newYPosition += viewportHeight - diff;
    }

    // animate new positions
    this.tag('Items').patch({
        smooth:{y: newYPosition}
    });

    // and store the new index
    this._storedPage = currentPage;
}
```

This will move the focus down to the point where it reaches the end of the list, when it tries to change to focus to an item thats outside the viewport it will move the complete list up so the new focused element is in the top of the viewport.
