### ISSUE TITLE
Will you have some native "longpress  handleKey" support?

### ISSUE THREAD

**Issue by skHazard** [WebPlatformForEmbedded/Lightning#48]
Did'n find anything about longpress native events in the docs.  Maybe you can recommend some best practices?
Now I having issues, when doing my own event listeners, and I have multiple nested views with _handleEnter method, it worked not very well for now  - both enter and long-enter work and I'm still looking for some better options.
Thanks! #

**Comment by erikhaandrikman** [comment]
Hey, this is indeed not the docs. For long press to work work we need to register and listen keyup events, and Lightning current is not, we only listen keydown events. To create some best practices we first need to register keyup events so we can create some configurable long press handlers.

**Comment by erikhaandrikman** [comment]
There is now an feature branch available that supports keyup and longpress:
https://github.com/WebPlatformForEmbedded/Lightning/tree/feature/Longpress

Depending on the exact keymapping you can set the following handlers on your component:
i.e Left:

```
// this will fire on normal keypress left
_handleLeft(){ 
}

// this will fire when you release the left key
_handleLeftRelease(){
}

// this will fire when you keep pressing left for a given time:
_handleLeftLong(){
}

// you can configure the timing (in ms) via the template
static _template(){
 return {
  w: 100, h:100,
  longpress:{left:600, up:800, right:1200, down:400}
 }
}

```
