### ISSUE TITLE
ref ignored when add a child via `add()`

### ISSUE THREAD

**Issue by michielvandergeest** [WebPlatformForEmbedded/Lightning#49]
I found that when adding a child using the `add()` method with an object literal, the `ref` key seems to be ignored / not updated. When overwriting the `childrens` array directly, the `ref` is honoured.

Example to reproduce:

```js
let view = {
   ref: 'Home',
   type: Home,
}
this.tag('Content').add(view)
console.log('get by ref', this.getByRef(view.ref)) // returns undefined
console.log('tag', this.tag(view.ref)) // returns StateMachineRouter
```

Expected behaviour: `this.getByRef(view.ref)` to return the StateMachineRouter as well

**Comment by erikhaandrikman** [comment]
getByRef will only search through the refs of the affected ObjectList. this.getByRef(view.ref) will result in undefined, while this.tag("Content").getByRef(view.ref) will return the correct component.

Also, this.tag(view.ref) will search through all the tags of the tree and return the component you're looking for.

**Comment by michielvandergeest** [comment]
Yeah, this makes sense now. Thanks for explaining the difference between `this.getByRef` and `this.tag` 👍
