### ISSUE TITLE
Loading Offscreen Images

### ISSUE THREAD

**Issue by imrobertloucans** [WebPlatformForEmbedded/Lightning#57]
I am rendering a list component that is image intensive - I noticed that the image textures do not force a download until the image is very close to on screen. 

Example - if I have 21 image textures created in the list,  with 7 on screen and the 11th item in the center of the list - leaving 14 offscreen.   only 9 images will be retrieved.  

This is ok for single item page,  but multiple item pages causes lag in image download and render and overall poor ux.  is it possible to force offscreen image texture to load to see if this ux can be improved?

**Comment by erikhaandrikman** [comment]
You can tweak the within bounds calculations by defining some extra margins so you can force images to load before they're almost within renderable viewport (and will also invoke _active / _firstActive lifecycle events earlier)

You can do this via the boundsMargin property:

```
static _template(){
  return {
     MyListWrapper:{
       // margins: left, top, right, bottom.
        boundsMargin:[400,0,0,0], type: SomeType
     }
  }  
}
```
This will take an extra 400px (left) in account when calculating if the component is within bounds.

**Comment by erikhaandrikman** [comment]
Does this solve the problem? And can we close the issue?

**Comment by imrobertloucans** [comment]
👍
