### ISSUE TITLE
Tizen 2.3 (2015 TV)

### ISSUE THREAD

**Issue by fana605** [WebPlatformForEmbedded/Lightning#63]
Hi,
On the docs, you state that:

> In terms of performance, it runs awesome on WebOS and (modern) Tizen

What do you mean by modern Tizen? 
I'm trying the demo on a Samsung Smart TV 2015 (Tizen 2.3) and I get only a black screen.
I get a warning on the console: 

> Can't use image worker because browser does not have createImageBitmap and Web Worker support

I tried to disable image worker and the warning stopped showing, but the result is the same.

Working fine on my computer browser.

What are the minimum requirements? Or is there some settings I could disable to support older browsers?

**Comment by erikhaandrikman** [comment]
We expect a browser to have a canvas element with WebGL (or as fallback 2dcontext) support. We did some successful test on Tizen 2.4.0 and higher but haven't tested 2.3.0. Inside our SDK are some build scripts to create a bundle for web which also transpiles the codebase to ES5 (which is required for 2.3.0)

> Can't use image worker because browser does not have createImageBitmap and Web Worker support

The warning is just to notify you that the browser has no WebWorkers and CreateImageBitmap support and uses the fallback. Lightning uses image worker to have off threaded image support.

**Comment by erikhaandrikman** [comment]
Closing this ticket for now
