### ISSUE TITLE
Flexbox performance issue 

### ISSUE THREAD

**Issue by MykhailoDz** [WebPlatformForEmbedded/Lightning#65]
Quoted from: https://webplatformforembedded.github.io/Lightning/docs/renderEngine/flexbox

> Lightning does not contain the bloated HTML CSS toolbox. 
Instead, it only contains the useful Flexbox layout methodology. 
The Lightning layout engine has some smart performance optimizations. 
However, it is still rather CPU-intensive so it is best used for situations in which the flex items do not often change dimensions.
>

Q: Is there some performance issues if we have a carousel card if it has resized on focus/unfocus?
The point is that the flex is not used on the card itself but rather on the text items included.
Example: 
static _template() {
    return  {
        clipping: true,
        mount: 0.5,
        BackgroundImage: {
            mount: 0.5,
            x: (w)=> w / 2,
            y: (h) => h / 2
        },
        Overlay: {
            mount: 0.5,
            x: (w)=> w / 2,
            y: (h) => h / 2,
            rect: true,
            color: color.overlay.overlay_200
        }, 
        TextContainer: {
            mount: 0.5,
            flex: {
                direction: 'column',
                alignContent: 'center',
                justifyContent: 'center',
                paddingTop: 20
            }, 
            Title: {
                flexItem: {
                    alignSelf: 'center'
                },
                text: {
                    fontSize: 32,
                    fontFace: 'Medium',
                    textColor: color.button.text,
                    textAlign: 'center'
                }
            },
            Underline: {
                alpha: 0,
                flexItem: {
                    alignSelf: 'center'
                },
                rect: true,
                w: 120,
                h: 4
            }
        }
    };
}

Thank you.

**Comment by g-zachar** [comment]
Hi @MykhailoDz 

The use case you're describing shouldn't be an issue. Of course, the more items you include in flex layout and the more forced recalculations happen (via dimension resize) the more CPU will be needed.

However, this does not mean you shouldn't use flex. When it comes to performance, general approach is profiling the app and making sure the code is clean and doesn't do anything unreasonable.

Best regards

**Comment by g-zachar** [comment]
Closing for now, please reopen if you have any further doubts.
