### ISSUE TITLE
Viewport issue

### ISSUE THREAD

**Issue by MykhailoDz** [WebPlatformForEmbedded/Lightning#66]
While developing we faced with viewport issue.
![ezgif-1-339113329d2b](https://user-images.githubusercontent.com/46669878/67856959-5e3a9900-fb1e-11e9-89ea-03a689202731.gif)

You can see on the gif that the lower one carousel is disappearing.

**Comment by erikhaandrikman** [comment]
It seems like the lower grid is indeed disappearing but the title is still visible. Can you provided us a part of the source so we can investigate?

**Comment by erikhaandrikman** [comment]
Problem was in the definition of the boundsMargin in the listComponent, by either removing the boundMargin or specifying a number larger then 0 for the top we managed to fix the problem.

Closing the ticket for now.
