### ISSUE TITLE
Rounded images

### ISSUE THREAD

**Issue by yuraantonov11** [WebPlatformForEmbedded/Lightning#70]
Hello, is there a simple way to render a rounded image(without using `getCanvasTexture`)?

**Comment by g-zachar** [comment]
Hi @yuraantonov11 
Yes, there is pretty strightforward way to do this using `RadialFilter` shader:

```javascript
Base: {
  rtt: true,
  w: 100,
  h: 100,
  Inner: {
    shader: {
      type: lng.shaders.RadialFilter,
      radius: 50
    },
    src: "image",
  },
}
```

[Example](https://jsfiddle.net/tn65mc4u/)

Best regards

**Comment by yuraantonov11** [comment]
Hi @g-zachar, thanks for your answer, I try to render some images(not only squares) with rounded corners. e.g.: 
![image](https://user-images.githubusercontent.com/9784945/68694995-e2f7cf00-0582-11ea-8a4e-7908b081fe46.png)
How can I set different radiuses?

**Comment by yuraantonov11** [comment]
Can anyone answer my question?

**Comment by g-zachar** [comment]
@yuraantonov11 I added shader for this specific purpose in 1.3.0, let me know if you have any further questions (you can check example [here](https://jsfiddle.net/b02e34td/3/)).

**Comment by yuraantonov11** [comment]
@g-zachar, thanks for your answer, but I have one more question. Can I set rounding to different corners?

**Comment by g-zachar** [comment]
@yuraantonov11 , it is not possible per se, but you can work around it by clipping parts of image that is being rounded ([example](https://jsfiddle.net/rs4pvno5/))
