### ISSUE TITLE
Issue with RoundedRectangle shader

### ISSUE THREAD

**Issue by yuraantonov11** [WebPlatformForEmbedded/Lightning#73]
Hi, after adding this code to my comonent:
```javascript
   rtt: true,
        shader: {
            type: lng.shaders.RoundedRectangle,
            radius: ROUND_RADIUS
        },
```

I have got blinking screen issue with this error:
https://drive.google.com/file/d/1leM24VeNam2XTlBiha9AcVrJldG2f2yR/view?usp=sharing

**Comment by g-zachar** [comment]
Hi @yuraantonov11 

Can you provide more context to this issue? Does this happen when you use different shaders in this context aswell?

Best regards

**Comment by yuraantonov11** [comment]
Hi @g-zachar, I have a carousel with cards, and after added rounded corners to the card I have this [Carousel Image.](https://drive.google.com/open?id=1orNcMPbCVKwetmyEL3IBy6WTlKXjVj68)
```javascript
            Content: {
                rtt: true,
                shader: {
                    type: lng.shaders.RoundedRectangle,
                    radius: ROUND_RADIUS
                },
```

**Comment by g-zachar** [comment]
Closing for now, please reopen if it's still relevant. I couldn't reproduce the issue myself.
