### ISSUE TITLE
get active component (last component in focus path) from Parent component

### ISSUE THREAD

**Issue by AndriyShpyra** [WebPlatformForEmbedded/Lightning#76]
During the development, in console, we can view the whole focus path.
Is it possible from the Parent component to get an active, focused component, without using fireAncestors or signals?

**Comment by erikhaandrikman** [comment]
You can access the focus path from any component: `this.application.focusPath` will return an array, and last item it current focused Component

**Comment by AndriyShpyra** [comment]
thank you
