### ISSUE TITLE
Web Browser Documentation issues

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#79]
Hello,

referring to: [Web Browser](https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/web )

- After run `npm i` I cannot find `dist/lightning-wpe.js`
- If I run `npm run build` I can find `dist/lightning.js`, `dist/lightning.min.js`, `dist/lightning.min.js.map` but not `lightning-web.js`.
- Are `lightning-wpe.js` and lightning-web.js two different files?
- Where to create `index.html`?

**Comment by erikhaandrikman** [comment]
Hey, at this moment we’re working on the next version of our SDK. You can find the blueprint for working with it here: https://github.com/WebPlatformForEmbedded/Lightning-SDK-blueprint/tree/next

I suggest trying it out

**Comment by michal-krasowski-red** [comment]
@MattiaPontonioKineton , I have replaced `dist/lightning-web.js` with `dist/lightning.es5.js` in the examples. 

@erikhaandrikman, are you dropping the Lightning project in favor of 'Lightning-SDK-bluepring'?
Why is the development done separately from the main repo? It is really confusing.

**Comment by michielvandergeest** [comment]
@michal-krasowski-red the blueprint is deprecated in favour of the Lightning-CLI approach. See more details in the readme here: https://github.com/WebPlatformForEmbedded/Lightning-SDK-blueprint
