### ISSUE TITLE
Object doesn't support property or method '_setParent'

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#81]
When I try to add a new child using `childList.add` method I get this error:
`Object doesn't support property or method '_setParent'`
This is my _init() method from the doc example:
```
_init() {
        // let's generate dinamically some list items 
        // and give it to our list
        this.tag('List').items = [1,2,3,4].map((i) => ({label: i }));
        this.tag('List').childList.add({ 
            type: ExampleListItem,
            x: 4 * 70,
            item: {label: 5}
        });
        
    }
```
I can't figure out how to add a new item from scratch without passing by the template.
REF: https://webplatformforembedded.github.io/Lightning/docs/renderEngine/elements/children

**Comment by erikhaandrikman** [comment]
Childlist add() function expects an Element as it's parameter, and not a literal object. You could use the childLists a() method and feed it with a literal object (or an array of objects)

```
this.tag('List').childList.a({ type: ExampleListItem });
```
https://github.com/WebPlatformForEmbedded/Lightning/blob/66917a4418c3dd28eceb1d29a420e71a3def74a5/src/tree/ObjectList.mjs#L146

You could also, first create the Element:

`const item = this.stage.c({type: ExampleListItem});`

and then add it to the child list:

`this.tag('List').childList.add(item);`
