### ISSUE TITLE
Usage of Light3dComponent 

### ISSUE THREAD

**Issue by lk-mlogical** [WebPlatformForEmbedded/Lightning#82]
Could you please provide me more information or usage of Light3dComponent?

My requirement is as below
https://drive.google.com/file/d/1qa1Fj_pePxZ_yrHwmHBJhhPepI40KCiL/view?usp=sharing

The focused list item should change the shader position based on the key direction.

Does it fit Light3d Shader for my requirement or could you please suggest?

**Comment by g-zachar** [comment]
Hey @lk-mlogical,

As far as I'm concerned, `Light3dComponent` is part of SDK and is deprecated.

Instead, if I understood your question correctly, you can use `Light3dShader` directly as in this [example](https://jsfiddle.net/137sfxhk/1/).

Best regards

**Comment by lk-mlogical** [comment]
Hi @g-zachar, you are right. I am looking to integrate Light3dShader into my app. But I found the right usage of this shader in one of our apps. Thanks for sharing the example. This example might help me as well. Hence I am closing this issue. Once again thanks for your comment.
