### ISSUE TITLE
fontFace list

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#84]
Referring to https://webplatformforembedded.github.io/Lightning/docs/textures/text

Name | Type | Default | Description
-- | -- | -- | --
fontFace | Integer | null | Font-family used for current text.

where to find the list of Font faces avalible?

**Comment by erikhaandrikman** [comment]
Lightning is using 'sans-serif' as a default fontFace, but if you want to use different fonts you need to add them yourself: 

_without SDK:_ 

```
@font-face {
      font-family: YourFontName;
      src: url(font/yourFont.ttf) format('truetype');
}
```

Make it available by writing something to the browser via HTML: 

```
<head>
  <style>
    .MyFont{
        font-family: YourFontName;
        visibility: hidden;
        position: absolute;
    }
  </style>
</head>
<body>
        <div class="MyFont">.</div>
</body>
```

And use it: 

```
Label: { 
  text: { text:"Hello world!", fontFace: "YourFontName" }
}
```

_If you are using our SDK:_ 

https://github.com/WebPlatformForEmbedded/Lightning-SDK

You can add and an array of fonts to _getFonts() method and use them in your Components.

```
static getFonts() {
    return [
        {family: 'YourFontName', url: 'font/yourFont.ttf', descriptors: {}}
    ];
}
```

And use it: 

```
Label: { 
  text: { text:"Hello world!", fontFace: "YourFontName" }
}
```

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton 

Adding to @erikhaandrikman's answer:

Lightning uses `canvas2d` to render text, therefore it can use fonts that are available within browser and page's context (specific font is passed as string via Lightning api calls that trace up to template itself, with `sans-serif` set as default as @erikhaandrikman mentioned).

Therefore fonts can be registered with standard web way (with either CSS or `document.font` API).

Coming to your question, standard web API does not provide a good way to list available fonts(https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts).

There is also [discussion](https://stackoverflow.com/questions/3368837/list-every-font-a-users-browser-can-display) on StackOverflow on this topic and proposed solutions.

Lightning doesn't provide such functionality neither.
