### ISSUE TITLE
Value passed to transition event listeners

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#89]
If I pass console.log as a event listener of transition like:
```
this.tag("LilLightningA").transition('x').on('start', console.log);
```
I get values in console like:
`0.08289999910630286 undefined undefined`
What are these values? 
There is a Event object that i can use inside listeners?

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton,

Many of Lightning's elements are event emitters (stage, components, animations, transitions). You can register on their events (like you did) and handle them asynchronously. Some of the events contain data associated with them (most don't), that is passed as up to 3 arguments to function you register.

In your example, `start` event shouldn't have any data associated with it, however `progress` will have its current value passed as first argument to your callback.

More notable events with data associated with them are:
```
(animation) progress - current progress, undefined, undefined
(animation) repeat - repeats left, undefined, undefined
(transition) progress - current progress, undefined undefined
(element) txError - load error, texture source, undefined
(element) txLoaded - texture source, undefined, undefined
(element) txUnloaded - texture source, undefined, undefined

* Note: elements are part of Lightning's internal virtual DOM, Components derive from elements
```

Let me know if you have any further questions.

Best regards

**Comment by MattiaPontonioKineton** [comment]
Hi @g-zachar ,

thanks for You response.
Just the request of updating the Doc with this informations.

Best regards
