### ISSUE TITLE
How to change background color of the App

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#90]
Referencing [this](https://github.com/WebPlatformForEmbedded/Lightning-CLI/issues/3).

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton,

you should be able to do it with setting `clearColor` value of Lightning app's stage setting:

[reference](https://webplatformforembedded.github.io/Lightning/docs/gettingStarted/configuration)

Best regards

**Comment by MattiaPontonioKineton** [comment]
Hi @g-zachar,

thanks for Your response.
Now it works.
The source of **index.js**:
```
import { Launch } from 'wpe-lightning-sdk'
import App from './App.js'

export default function() {
  const options = {stage: {w: 1920, h: 1080, clearColor: 0xFF223366}}
  return Launch(App, options, ...arguments)
}
```
