### ISSUE TITLE
[Key Handling] Test _handleBack when developing in browser

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#92]
Is possible to test `_handleBack` method in browser?
Others methods like `_handleLeft`  or `_handleRight`  is reactive with arrow Keys.

**Comment by g-zachar** [comment]
@MattiaPontonioKineton 

Backspace should work.

**Comment by MattiaPontonioKineton** [comment]
@g-zachar Yes it works. Thank You!
