### ISSUE TITLE
Reference to HTMLVideoElement

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#94]
Hello,

cosidering this example:
https://webplatformforembedded.github.io/Lightning/docs/player/player
where to find a reference "in the framework" to the [HTMLVideoElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement) in order to call the methods?

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton 

Player is part of [Lightning SDK](https://github.com/WebPlatformForEmbedded/Lightning-sdk), if this is still a problem, please create issue there.

Best regards
