### ISSUE TITLE
video is behind the canvas

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#95]
Hello, in my app I found the following situation after try to implementing the video player from
https://webplatformforembedded.github.io/Lightning/docs/player/player
starting from a customization of
https://github.com/WebPlatformForEmbedded/Lightning-Demo-App
Here's the situation of the CSS:
```
/* video */
element.style {
    position: absolute;
    z-index: 1;
    display: none;
    visibility: visible;
    left: 0px;
    top: 0px;
    width: 1920px;
    height: 1080px;
}
canvas {
    position: absolute;
    z-index: 2;
}
```
so the video is behind the canvas.
If I hide the canvas with inspector the video is correctly shown.
My question is what is the "best" way to working around this issue? There are some configs to set?

**Comment by Thomvl** [comment]
Hi @MattiaPontonioKineton ,
Usually on the Settopboxes the Browser and the actual player are seperate processes, where the browser overlaps the player.  Due to this reason we mimic the same behaviour of putting the video behind the app. 

Solution for this can be found in #72

**Comment by MattiaPontonioKineton** [comment]
@Thomvl thanks for Your reference. 
I've read it.
So, how can I put my custom controls over the video and by developing in browser correctly se the video `plays`, `pauses`, and so on?
I have to "cut" the player with a `shader`?
How can I do it?

Best regards
Mattia

**Comment by Thomvl** [comment]
Depending on te type of design that you want to achieve you can either make the cutout smaller, or when they over over the 'hole' make sure that you put the shader on a different renderbranch than the buttons are. 

The shader will only be applied to everything in the renderbranch that it is being applied to, so if you make a new render branch for your player controls they should not be affected.
