### ISSUE TITLE
Lightning not working on TV's decoder

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#96]
Hi,

I'm testing a customization of 
https://github.com/WebPlatformForEmbedded/Lightning-Demo-App
into a browser into a decorder in TV.
The serving from server is Ok, so the html files are correctly sent.
Here's an example log from `http-server` where find the user agent:
```
[2020-01-15T13:52:11.360Z]  "GET /lightning-demo-app.html" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.6.0 Chrome/45.0.2454.101 Safari/537.36, Sky_STB_ST419_2018/1.0.0 (Sky, ES240IT, )"
```
The demo app that is correctly shown in Chrome not working in this test, showing a black screen.
Seems the propblem should be related to the `type="module"` of the script because norma Javascript in a normal script tag works.
My questions are:

- There is a best practice of building the app and serving it in order to guarantee compatibility?
- Is this process documented or open in some issue trought this repositories?

Please consider that I'm tryiing to test the demo app with his features like Sliders, and so on so I'm looking to a way to customize this code base in a safe manner.

Best regards
Mattia

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton ,

the usual problems when trying to run web applications on embedded platforms are browser limitations, e.g:

* insufficient support of ES6 syntax and features
* insufficient support for certain web standards (e.g. web workers, webgl API)
* javascript runtime overhead (should not be the case here)

Those usually need to be investigated and solved on per platform basis. Lightning is running on quite large number of different platforms making it less likely to fail but it still can happen.

Best regards

**Comment by MattiaPontonioKineton** [comment]
Hi @g-zachar ,

thanks for Your response.
Should be `lng build` from
https://github.com/WebPlatformForEmbedded/Lightning-CLI
a solution?
I'm a bit in trouble "mixing" the two folder structures, the one generated from `lng build` and the one present as default in 
https://github.com/WebPlatformForEmbedded/Lightning-Demo-App

Best regards

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton 

Lightning-CLI is new thing, probably in it's alpha stage (I'm not personally involved in it, perhaps best to ask its maintainer for any help related to that).

For stable solution you can try running [this](https://github.com/WebPlatformForEmbedded/Lightning-sdk-blueprint).

However, if you're encountering any of the aforementioned problems, then this solution doesn't address them (yet).

Best regards
