### ISSUE TITLE
Solution for debugging and logging in TV

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#98]
Hello,

I'm looking for a solution for troubleshooting eventual problems developing in TV.
There is a solution already available?
A logger?
A developer tool?
Something build-in in the framework?
Now I've started to find a solution via JavaScript and HTML, see this [question](https://stackoverflow.com/questions/59757206/insert-console-content-into-html).

Best regards
Mattia

**Comment by g-zachar** [comment]
Hi @MattiaPontonioKineton 

there is nothing of this sort in Lightning (we work with browsers that enable developer tools for the most part).

However your solution is a good approach if you don't have access to more sophisticated tools.

Best regards
