### ISSUE TITLE
Benefit from Feature/es5 bundle as a dependency

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [WebPlatformForEmbedded/Lightning#99]
Is possible to benefit from this build files using **Lightning** as a **npm dependency**?
Is even possible using **Lightning-SDK**?
You have to use a **bundler** in Your custom project?
Commit reference: be1a4313c5528f4c4038c7f9dfe755cc2c18480e

**Comment by g-zachar** [comment]
Closing for now, please reopen if still relevant and I'll address your question in more detail.
